require 'cocoapods-deploy/deploy_analyzer'
require 'cocoapods-deploy/deploy_downloader'
require 'cocoapods-deploy/deploy_installer'
require 'cocoapods-deploy/deploy_transformer'
require 'cocoapods-deploy/command'
require 'cocoapods-deploy/patches/write_lockfile_patch'
